### ISSUE TITLE
Certificate for HTTPS

### ISSUE THREAD

**Issue by jubueche** [lucadentella/esp32-tutorial#11]
How do I get the SSL certificate? I am hosting my webpage on Azure and use Cloudflare as a proxy. Can I just generate an certificate with openssl?

**Comment by aureq** [comment]
@jubueche Did you check with [Cloudflare](https://support.cloudflare.com/hc/en-us/articles/200170516-How-do-I-add-SSL-to-my-site-)? Option 1 seems to be what you're after... You may also want to look at Let's Encrypt SSL too.

**Comment by jubueche** [comment]
Sorry that was a stupid question. I watched a video on SSL and now I understand it. We need the certificate so that the server can authenticate itself and we are not prone to man in the middle attacks. I simply had to get the Baltimore (MSFT) certificate and it worked.
