### ISSUE TITLE
Having trouble creating ssl certificate

### ISSUE THREAD

**Issue by ENGRsao** [lucadentella/esp32-tutorial#18]
Running the line of code

 winpty openssl ca -config openssl.cnf -extensions server_cert -days 365 -notext -md sha256 -in csr/espserver.csr -out certs/espserver.cer

and i keep getting the error

Using configuration from openssl.cnf
Error opening CA private key /home/Hakeem/myCA/private/ca.key
9360:error:02001003:system library:fopen:No such process:bss_file.c:406:fopen('/home/Hakeem/myCA/private/ca.key','rb')
9360:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:408:
unable to load CA private key

how can I  resolve this?

**Comment by lucadentella** [comment]
Hi, it seems you are missing the certificate authority file (ca.key), please follow [the tutorial](http://www.lucadentella.it/2017/08/25/esp32-21-mutua-autenticazione/).
