### ISSUE TITLE
30_https_ota: versioning using doubles

### ISSUE THREAD

**Issue by svenfuchs** [lucadentella/esp32-tutorial#21]
https://github.com/lucadentella/esp32-tutorial/blob/master/30_https_ota/main/main.c#L95

```
if(new_version > FIRMWARE_VERSION) {
  ...
```

Wouldn't this stop working going from `0.9` to `0.10`? 

😄

**Comment by lucadentella** [comment]
well... yes! after 0.9 make sure you go with v1.0 :D
