### ISSUE TITLE
30_https_ota - Potential man-in-the-middle attack vulnerability

### ISSUE THREAD

**Issue by rpelicia** [lucadentella/esp32-tutorial#22]
I think I found a potential security risk.
The code **does** check for authentication (using the certificate) while calling the "esp_https_ota" function:
```
	esp_http_client_config_t ota_client_config = {
		.url = file->valuestring,
		.cert_pem = server_cert_pem_start,
	};
```
But the code does **not** check for authentication while downloading the JSON file, which is just as critical:
```
		esp_http_client_config_t config = {
        .url = UPDATE_JSON_URL,
        .event_handler = _http_event_handler,
		};
```
That is enough for a man-in-the-middle-attack, right?

Proposed fix:
```
		esp_http_client_config_t config = {
        .url = UPDATE_JSON_URL,
        .cert_pem = server_cert_pem_start,
        .event_handler = _http_event_handler,
		};
```
PS.: Sorry if this is not the proper channel. I'm new to github.

**Comment by rpelicia** [comment]
For example, an attacker could use DNS spoofing to redirect you to his own JSON file, pointing you to the address of his own malicious binary file. As long as his binary file is hosted on a legit domain with the SAME ROOT CERTIFICATE as the legit binary file's domain, the second authentication check will not detect the deception.

**Comment by lucadentella** [comment]
Hi, yes I think you're right... in a real scenario you'd probably perform additional checks (I worked on a real application that also digitally sign the firmware file).
