### ISSUE TITLE
Compilation Error - (.literal._Z17check_update_taskPv+0x30): undefined reference to `_binary_certs_pem_start'

### ISSUE THREAD

**Issue by SuvamNaskar** [lucadentella/esp32-tutorial#23]
Hello there, I am using Arduino IDE, I have changed the app_main() to setup(), and some minor changes. But I an getting the compilation error: 
`(.literal._Z17check_update_taskPv+0x30): undefined reference to `_binary_certs_pem_start'`
Can anyone please help me with that? Thanks

**Comment by lucadentella** [comment]
Hi, my tutorials are not intended for Arduino, but for the esp-idf framework.
